CREATE TABLE Record (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dateTimeCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    pulseTypeID INT UNSIGNED,
    PositionID INT UNSIGNED,
    FOREIGN KEY (pulseTypeID) REFERENCES PulseType(id),
    FOREIGN KEY (PositionID) REFERENCES HandPosition(id)
);
