version: "3.9"
services:
  piezo-server:
    build: .
    ports:
      - "8000:8000"
  mysql-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
