CREATE TABLE RecordSession(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dateTimeCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    piezoelectricRecordID INT UNSIGNED NULL,
    ecgRecordID INT UNSIGNED NULL,
    HandPositionID INT UNSIGNED NULL,
    FOREIGN KEY (piezoelectricRecordID) REFERENCES Record(id),
    FOREIGN KEY (ecgRecordID) REFERENCES Record(id),
    FOREIGN KEY (HandPositionID) REFERENCES HandPosition(id)
)