CREATE TABLE Record(
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  data TEXT,
  HandPositionID INT UNSIGNED NULL,
  dateTimeCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
  dateTimeUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)