CREATE TABLE Record(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    data TEXT,
    typeID INT UNSIGNED NOT NULL,
    dateTimeCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    dateTimeUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DiagnosisID INT UNSIGNED NULL,
    HandPositionID INT UNSIGNED NULL,
    FOREIGN KEY (DiagnosisID) REFERENCES Diagnosis(id),
    FOREIGN KEY (HandPositionID) REFERENCES HandPosition(id)
)